### ISSUE TITLE
angular.js:13642 TypeError: Cannot set property 'innerText' of undefined

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [FlemmingBehrend/feb-stepper#3] opened 2016-06-04 13:31 UTC
I am using this as shown i your example. 

Here is my HTML

```
<feb-stepper steps="['{{vm.stepNo1}}', 'Step 2', 'Step 3', 'Step 4', 'Step 5']" control="vm.stepperControl" start-step="1" step-lines="true"></feb-stepper>
<button ng-click="vm.stepperControl.prevStep()">Prev step</button>
<button ng-click="vm.stepperControl.nextStep()">Next step</button>
```

Here is my variables in controller

```
vm.stepperControl = {};
vm.stepNo1 = "test";
```

I have also injected the module in the main module `'feb.stepper'`

I am able to see the stepper in the page. But still it is giving me some error. Please check the below screenshot.

![screen shot 2016-06-04 at 7 00 15 pm](https://cloud.githubusercontent.com/assets/9896335/15799802/9f6466de-2a86-11e6-895d-b2c1e03763dc.png)

**Comment by FlemmingBehrend** [comment] 2016-06-04 21:35
Hi @rajeshwarpatlolla, 

I have just tried to create a new angular project and pulled down the feb-stepper with bower and I can not reproduce the problem. What I can see from your error, it fails when step1's text tries to be modified.

Could it be that your controllers scope (vm) is not bound to the html. Could you link the full html and controller?

Another thing is that the `step-lines="true"` is not supported by the component anymore. You should remove it from the html.

**Comment by FlemmingBehrend** [comment] 2016-11-03 18:51
Have not heard anything in a long while. I could not reproduce the error so I am closing this issue.

**Closed as completed by FlemmingBehrend** 2016-11-03 18:51 UTC
